name: Rust
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 8 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0

    - name: Set up Rust
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Create kind cluster
      run: kind create cluster --wait 5m

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        kind get kubeconfig > $HOME/.kube/config

    - name: Verify cluster
      run: kubectl cluster-info

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test

